name: Linting

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Restore cached modules
      uses: actions/cache@v2
      id: cache-packages
      with:
        path: node_modules
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Fallback if module cache fails
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Run ESLint
      run: npm run lint