name: PR Automation
on: pull_request_target

jobs:
  dependencies:
    name: Dependabot
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
    - name: Command Dependabot to merge after CI passes
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '@dependabot squash and merge'
          })